### ISSUE TITLE
Does Graphiti support directives?

### ISSUE THREAD

**Issue by cshadek** [GraphQLSwift/Graphiti#54]
I tried using @skip and @include in a query and they didn't seem to work.

**Comment by NeedleInAJayStack** [comment]
Graphiti does not support custom directives at this time, but the lower level [GraphQL package](https://github.com/GraphQLSwift/GraphQL) does.

As for `@skip` and `@include`, these are supported by any Graphiti schema (provided by the GraphQL package [here](https://github.com/GraphQLSwift/GraphQL/blob/main/Sources/GraphQL/Type/Directives.swift)), since they are part of the GraphQL spec.
